# Generated by Django 3.2.6 on 2021-09-09 15:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', ckeditor.fields.RichTextField()),
                ('detail', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='page-images')),
            ],
            options={
                'verbose_name': 'Main_page',
                'verbose_name_plural': 'Main_pages',
                'db_table': 'Main_pages',
            },
        ),
    ]
