from cosmosit.models.hero import Hero
from cosmosit.models.about import About
from cosmosit.models.features import Features
from cosmosit.models.services_headers import ServiceHeaders
from cosmosit.models.detail import Detail
from cosmosit.models.call_action import CallAction
from cosmosit.models.team import TeamMembers
from cosmosit.models.contact import Contact
from cosmosit.models.icons import Icons
from cosmosit.models.testimionals import Testimionals