# Generated by Django 3.2.6 on 2021-09-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero1', models.CharField(max_length=250)),
                ('h_service', models.CharField(max_length=90)),
                ('h_icon', models.ImageField(upload_to='header-icons')),
            ],
            options={
                'verbose_name': 'hero',
                'verbose_name_plural': 'heros',
                'db_table': 'hero',
            },
        ),
    ]
