# Generated by Django 3.2.6 on 2021-09-08 15:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cosmosit', '0002_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='section-images'),
            preserve_default=False,
        ),
    ]
