# Generated by Django 3.2.6 on 2021-09-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmosit', '0005_auto_20210908_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='header',
            field=models.CharField(blank=True, max_length=230, null=True),
        ),
    ]
