# Generated by Django 3.2.6 on 2021-09-08 16:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cosmosit', '0006_alter_about_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='section-images')),
                ('ficon', models.ImageField(upload_to='icons')),
                ('content', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'list',
                'verbose_name_plural': 'lists',
                'db_table': 'list',
            },
        ),
        migrations.CreateModel(
            name='ServiceHeaders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header1', models.CharField(max_length=60)),
                ('header2', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'service_header',
                'verbose_name_plural': 'service_headers',
                'db_table': 'service_header',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'title',
                'verbose_name_plural': 'titles',
                'db_table': 'title',
            },
        ),
        migrations.RemoveField(
            model_name='about',
            name='list',
        ),
        migrations.AlterField(
            model_name='about',
            name='content',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about',
            name='header',
            field=models.CharField(default=django.utils.timezone.now, max_length=230),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hero',
            name='h_icon',
            field=models.ImageField(upload_to='icons'),
        ),
    ]
