# Generated by Django 3.2.6 on 2021-09-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmosit', '0007_auto_20210908_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_action_title', models.CharField(max_length=50)),
                ('call_action_text', models.CharField(max_length=75)),
            ],
            options={
                'verbose_name': 'call_action',
                'verbose_name_plural': 'call_actions',
                'db_table': 'call_action',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('full_name', models.CharField(max_length=150)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contact',
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='team-images')),
                ('full_name', models.CharField(max_length=40)),
                ('jobs', models.CharField(max_length=25)),
                ('information', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'db_table': 'Team Member',
            },
        ),
    ]
