# Generated by Django 3.2.6 on 2021-09-08 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosmosit', '0008_callaction_contact_teammembers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='h_icon',
        ),
    ]
