# Generated by Django 3.2.6 on 2021-09-08 17:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cosmosit', '0010_auto_20210908_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='list_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
