# Generated by Django 3.2.6 on 2021-09-08 17:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cosmosit', '0011_list_list_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='title_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
