# Generated by Django 3.2.6 on 2021-09-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmosit', '0012_title_title_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callaction',
            name='call_action_text',
            field=models.CharField(max_length=180),
        ),
        migrations.AlterField(
            model_name='callaction',
            name='call_action_title',
            field=models.CharField(max_length=120),
        ),
    ]
