# Generated by Django 3.2.6 on 2021-09-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmosit', '0013_auto_20210908_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=250)),
                ('detail', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'detail',
                'verbose_name_plural': 'details',
                'db_table': 'detail',
            },
        ),
        migrations.DeleteModel(
            name='List',
        ),
        migrations.DeleteModel(
            name='Title',
        ),
    ]
