# Generated by Django 3.2.6 on 2021-09-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmosit', '0014_auto_20210909_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimionals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=240)),
                ('image', models.ImageField(upload_to='testimionals-images')),
            ],
        ),
    ]
