# Generated by Django 3.2.6 on 2021-09-09 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosmosit', '0015_testimionals'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimionals',
            options={'verbose_name': 'testiminonal', 'verbose_name_plural': 'testimionals'},
        ),
        migrations.AlterModelTable(
            name='testimionals',
            table='testimional',
        ),
    ]
