from main_pages.views.get_started import get_started
from main_pages.views.about import about
from main_pages.views.services import services
from main_pages.views.team import team
from main_pages.views.marketing import marketing
from main_pages.views.product_management import product_management
from main_pages.views.prices import pricing
from main_pages.views.graphic_design import graphic_design
from main_pages.views.terms import terms
from main_pages.views.web_design import web_design
from main_pages.views.web_development import web_development